apiVersion: v1
kind: Service
metadata:
  name: e2e-pipeline
  namespace: pipeline
  labels:
    app: e2e-pipeline
spec:
  type: ClusterIP
  selector:
    app: e2e-pipeline
  ports:
    - name: https
      port: 8443
      targetPort: https
      protocol: TCP
    - name: listenhttp
      port: 19090
      targetPort: listenhttp
      protocol: TCP